language:
  - python

sudo:
  - false
  
python:
  - 3.5
  - 3.6
  
before_install:
  - pip3 install -r requirements.txt
  - pip3 install -r requirements-dev.txt
  - pip3 install -r requirements-tests.txt

script:
  - flake8 crypto_django
  - pycodestyle crypto_django
  - pylint crypto_django
  - coverage run --source=crypto_django -m unittest discover && coverage report -m
